#!/bin/bash

if [ "$(whoami)" = "root" ];
then
  chmod 755 scanp;
  echo "[*] installing...";
  $('pip3 install -r requirements.txt')
  mv ./scanp /usr/local/bin/scanp;
  echo "[*] installed!!";
else
  echo '[!] Execute in script user root...';
  echo "[!] Error and install...";
fi




