#!/usr/bin/python3
#coding: utf-8
try:
  import socket, sys, os
  import subprocess
  from datetime import datetime
except ImportError:
  print("[!] Error in model")


banner = '''\033[31m
  ██████  ▄████▄   ▄▄▄       ███▄    █  ██▓███  
\033[32m▒██    ▒ ▒██▀ ▀█  ▒████▄     ██ ▀█   █ ▓██░  ██▒
\033[34m░ ▓██▄   ▒▓█    ▄ ▒██  ▀█▄  ▓██  ▀█ ██▒▓██░ ██▓▒
\033[36m  ▒   ██▒▒▓▓▄ ▄██▒░██▄▄▄▄██ ▓██▒  ▐▌██▒▒██▄█▓▒ ▒
\033[35m▒██████▒▒▒ ▓███▀ ░ ▓█   ▓██▒▒██░   ▓██░▒██▒ ░  ░
\033[33m▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░ ▒▒   ▓▒█░░ ▒░   ▒ ▒ ▒▓▒░ ░  ░
\033[37m░ ░▒  ░ ░  ░  ▒     ▒   ▒▒ ░░ ░░   ░ ▒░░▒ ░
\033[36m░  ░  ░  ░          ░   ▒      ░   ░ ░ ░░
\033[32m      ░  ░ ░            ░  ░         ░
\033[31m         ░
\033[0;0m
'''
def scan():
    t1 = datetime.now()  
    subprocess.call('clear')
    ip = sys.argv[1]
    ips = socket.gethostbyname(ip)
    print (banner)
    print("\033[31m-\033[0;0m" * 60)
    print("Scanning Host::", ips)
    print("\033[33m-\033[0;0m" * 60)
    for port in range(1, 65535):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)
        result = s.connect_ex((ip, port))
        if result == 0:
           print(f"[!]Port {port}..........[Open]" )
        #else:
           #print(f"[!]Port {port}........[Closed]" )
    t2 = datetime.now()
    total = t2 - t1
    print("-" * 60)
    print("Scanning Completed in:", total)
    print("-" * 60)
    s.close()
try:
  if len(sys.argv) >= 2:
    scan()
  else:
    print("[!] Usage scanp <ip>\n")
except socket.gaierror:
    print("[!] Hostname not resolved!!\n")
except KeyboardInterrupt:
    print("[!] Stop!!\n")
except socket.error:
    print("[!] Server not responding!!")
except NameError:
    pass
