#!/usr/bin/python3
try:
  import nmap, sys, os, socket
  from datetime import datetime
except ImportError:
  print("\033[41m[!]\033[0;0m Error in lib")

def banner():
  os.system('clear')
  print('''\033[31m
 ██████╗ ██████╗ ██████╗  █████╗ ██╗
\033[32m██╔═══██╗██╔══██╗██╔══██╗██╔══██╗██║
\033[35m██║   ██║██████╔╝██████╔╝███████║██║
\033[32m██║   ██║██╔═══╝ ██╔═══╝ ██╔══██║██║
\033[36m╚██████╔╝██║     ██║     ██║  ██║██║
\033[31m ╚═════╝ ╚═╝     ╚═╝     ╚═╝  ╚═╝╚═╝
\033[0;0m
  ''')
  print("\033[33m-\033[0;0m" * 60)
  print(f'\033[32m[*]\033[0;0m Scanning {ip} :: {host} ')
host = sys.argv[1]
ip = socket.gethostbyname(host)
def scan():
  t1 = datetime.now()
  #variaveis...
  global ip
  global host
  scanp = nmap.PortScanner()
  scanp.scan(host , '1-65535')  
  for host in scanp.all_hosts():
    print("\033[31m-\033[0;0m" * 60)
    print(f'\033[32m[*]\033[0;0m Host :: {host} :: {scanp[host].hostname()}' )
    print("\033[33m-\033[0;0m" * 60)
    print(f'\033[32m[*]\033[0;0m State :: {scanp[host].state()}' )    
    print("\033[31m-\033[0;0m" * 60)
    
    for proto in scanp[ip].all_protocols():
      print(f'\033[32m[*]\033[0;0m Protocol :: {proto}')
      print("\033[33m-\033[0;0m" * 60)
      
      phost = scanp[ip][proto].keys()
      
      for port in phost:
        print(f'\033[32m[*]\033[0;0m Port :: {port} :: State:: {scanp[host][proto][port]["state"]}')
  t2 = datetime.now()
  total = t2 - t1
  print("\033[32m-\033[0;0m" * 60)
  print("Scanning Completed in:", total)
  print("\033[31m-\033[0;0m" * 60) 
try:  
  if len(sys.argv) >= 2:
    banner()
    scan()
  else:
    print('\033[41m[!]\033[0;0m Usage : ./scanp2 <target>')
except KeyboardInterrupt:
  print('\033[41m[!]\033[0;0m Stop')
