#!/usr/bin/python3
#coding: utf-8
try:
  import random
  import socket, sys, os
  import subprocess
  from datetime import datetime
except ImportError:
  print("\033[36m[\033[33m!\033[31m]\033[0;0m Error in lib")

banner2 = '''\033[36m
\033[34m                .-'"""''---.___
\033[33m              .'               "'-.___
\033[36m            _'              _'-"'"""  """-
\033[37m           /    7        .'"              "->
\033[34m          .    .|     _-'                   '.
\033[31m         .  .'"  :   '.         _.------._  ''
\033[32m        .  -      . .'       .-'  "-   .' \ :
\033[33m        | '        >       .'.''"\"-   .'\"_'
\033[34m        |'        <      .'   :__/  : :_.':'
\033[37m     .--'-._      :   .--:     -._.'  '._.'
\033[36m    '>      '.     '. | '              .' :
\033[31m   '.        :'     '-'.____        .__.  '
\033[31m    /         :             :.          .'
\033[32m    \.       /              | '"-_  __-'
\033[37m      \.'-'"'         .'"":''    :-""""'.
\033[36m                     :   :               .
\033[31m                     |  :                :
\033[36m                     | :           .''.  :
\033[32m                     |.'.        _.:   '.:
\033[33m                     |    '---'""  :    :"
\033[35m                     |    '        :     :
\033[32m                     .'.___:._   .'    .
\033[37m                      .  '    '"'.     '
\033[36m                      |   :      '    :
\033[33m                      :    .    :    ' :
\033[31m        _.-'"'--..__   :   : . :    .  _:
\033[37m     .'      .       "-:   :   '   ..-"  :
\033[35m    (         '-       :   :._:   /   _.--"""--._
\033[34m     '          '. _....:  : .   / .-'           '.
\033[33m      '           :  ."" ""'-'  /-"               )
\033[32m       '._        :  :     ..-'                  /
\033[37m          '-._     \'' _ .'""""""'-.         _.-
\033[36m             .'--.__ .' '           - ____.-'
\033[32m            :         "":-.._______.'
\033[31m             '-.....-''"                                    \033[0;0m
'''

banner1 = '''\033[31m
  ██████  ▄████▄   ▄▄▄       ███▄    █  ██▓███  
\033[32m▒██    ▒ ▒██▀ ▀█  ▒████▄     ██ ▀█   █ ▓██░  ██▒
\033[34m░ ▓██▄   ▒▓█    ▄ ▒██  ▀█▄  ▓██  ▀█ ██▒▓██░ ██▓▒
\033[36m  ▒   ██▒▒▓▓▄ ▄██▒░██▄▄▄▄██ ▓██▒  ▐▌██▒▒██▄█▓▒ ▒
\033[35m▒██████▒▒▒ ▓███▀ ░ ▓█   ▓██▒▒██░   ▓██░▒██▒ ░  ░
\033[33m▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░ ▒▒   ▓▒█░░ ▒░   ▒ ▒ ▒▓▒░ ░  ░
\033[37m░ ░▒  ░ ░  ░  ▒     ▒   ▒▒ ░░ ░░   ░ ▒░░▒ ░
\033[36m░  ░  ░  ░          ░   ▒      ░   ░ ░ ░░
\033[32m      ░  ░ ░            ░  ░         ░
\033[31m         ░
\033[0;0m
'''
def scan():
    list = [banner1, banner2]
    r = random.choice(list)
    t1 = datetime.now()
    subprocess.call('clear')
    ip = sys.argv[1]
    to = []
    ips = socket.gethostbyname(ip)
    print(r)
    print("\033[31m-\033[0;0m" * 60)
    print("Scanning Host::", ips, "::", ip), os.system(f"fping {ip}")
    print("\033[33m-\033[0;0m" * 60)
    portu = [80,22,68,443,111,3306,1443,8003]
    print("\033[36m[\033[33m!\033[31m]\033[0;0mPort more usage::\n")
    for port in portu:
        s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)
        result = s2.connect_ex((ip, port))
        if result == 0:
          print(f"\033[36m[\033[33m!\033[31m]\033[0;0mPort {port}\\tcp\033[32m..........[Open]\033[0;0m" )
        else:
          print(f"\033[31m[!]\033[0;0mPort {port}\\tcp\033[32m....\033[31m!@....[Closed]\033[0;0m" )

    print("\n\033[36m[\033[33m!\033[31m]\033[0;0mChecking ports 1 to 65535::\033[0;0m\n")
    for port in range(1, 65535):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(1)
        result = s.connect_ex((ip, port))
        if result  == 0:
           to.append(port)
           print(f"\033[36m[\033[33m!\033[31m]\033[0;0mPort {port}\\tcp\033[32m..........[Open]\033[0;0m" )
        #else:
           #print(f"\033[31m[!]\033[0;0mPort {port}\\tcp\033[32m....\033[31m!@....[Closed]\033[0;0m" )
    t2 = datetime.now()
    total = t2 - t1
    print("\033[33m-\033[0;0m" * 60)
    print("Scanning Completed in:", total)
    print("Total in ports found:", to)
    print("\033[31m-\033[0;0m" * 60)
    s.close()
try:
  if len(sys.argv) >= 2:
    scan()
  else:
    print("\033[36m[\033[33m!\033[31m]\033[0;0m Usage scanp <ip>\n")
except socket.gaierror:
    print("\033[36m[\033[33m!\033[31m]\033[0;0m Hostname not resolved!!\n")
except KeyboardInterrupt:
    print("\033[36m[\033[33m!\033[31m]\033[0;0m Stop!!\n")
except socket.error:
    print("\033[36m[\033[33m!\033[31m]\033[0;0m Server not responding!!")
